//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wrcaysalesinventory.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wrcaysalesinventory.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRCay Hardware.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        public static string LabelAuditTrail {
            get {
                return ResourceManager.GetString("LabelAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string LabelCategories {
            get {
                return ResourceManager.GetString("LabelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LabelCustomers {
            get {
                return ResourceManager.GetString("LabelCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string LabelDashboard {
            get {
                return ResourceManager.GetString("LabelDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; Restore.
        /// </summary>
        public static string LabelDatabaseBackup {
            get {
                return ResourceManager.GetString("LabelDatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string LabelDeliveries {
            get {
                return ResourceManager.GetString("LabelDeliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string LabelExpenses {
            get {
                return ResourceManager.GetString("LabelExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Report.
        /// </summary>
        public static string LabelExpensesReport {
            get {
                return ResourceManager.GetString("LabelExpensesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string LabelGenSettings {
            get {
                return ResourceManager.GetString("LabelGenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string LabelInventory {
            get {
                return ResourceManager.GetString("LabelInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string LabelMaintenance {
            get {
                return ResourceManager.GetString("LabelMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Of Sale.
        /// </summary>
        public static string LabelPOS {
            get {
                return ResourceManager.GetString("LabelPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Settings.
        /// </summary>
        public static string LabelPOSSettings {
            get {
                return ResourceManager.GetString("LabelPOSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string LabelProduct {
            get {
                return ResourceManager.GetString("LabelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string LabelProducts {
            get {
                return ResourceManager.GetString("LabelProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string LabelReports {
            get {
                return ResourceManager.GetString("LabelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string LabelRestore {
            get {
                return ResourceManager.GetString("LabelRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        public static string LabelSearchProduct {
            get {
                return ResourceManager.GetString("LabelSearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Record.
        /// </summary>
        public static string LabelSearchRecord {
            get {
                return ResourceManager.GetString("LabelSearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string LabelStocks {
            get {
                return ResourceManager.GetString("LabelStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string LabelSubCategory {
            get {
                return ResourceManager.GetString("LabelSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LabelSupplier {
            get {
                return ResourceManager.GetString("LabelSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string LabelSuppliers {
            get {
                return ResourceManager.GetString("LabelSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Report.
        /// </summary>
        public static string LabelTransactionReport {
            get {
                return ResourceManager.GetString("LabelTransactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string LabelTransactions {
            get {
                return ResourceManager.GetString("LabelTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        public static string LabelTransactonHistory {
            get {
                return ResourceManager.GetString("LabelTransactonHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string LabelUpdate {
            get {
                return ResourceManager.GetString("LabelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LabelUsers {
            get {
                return ResourceManager.GetString("LabelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string LableDelivery {
            get {
                return ResourceManager.GetString("LableDelivery", resourceCulture);
            }
        }
    }
}
